<?php

$gel_stimulants = array(
					'gel1' => array(
									'picture' => 'assets/images/gel-stimulants/voulez-vous.gif',
									'picture-big' => 'assets/images/gel-stimulants/voulez-vous-big.gif',
									'name' => 'Voulez-vous',
									'description' => 'Gel lubrifiant Chaud Time au gout de Fruits Rouges',
									'definition' => 'Gel lubrifiant Chaud Time au gout de Fruits Rouges Appliquer ce gel stimulant sur les zones érogènes de votre corps ou celui de votre partenaire. Une sensation de chaleur et d\'excitation vous envoûte, le souffle de votre partenaire donne une chaleur ardente, et plus les caresses s\'accélèrent, plus l\'excitation monte. Un léger goût de fruit sucré ou de cocktail aphrodisiaque se répand dans l\'atmosphère ce qui vous pousse à laisser libre cour à votre imagination, le temps passe... l\'ambiance s\'électrise. N\'irrite pas les muqueuses Compatible avec les préservatifs Goût naturel / Sans parabènes Ne tache pas',
									'reference-store' => '4515484',
									'disponible' => '33',
									'prix' => '3.25',
								 	'prixLitre' => 39.75,
									'linkSite' => 'www.voulez-vous.com'													
									),

					'gel2' => array(
									'picture' => 'assets/images/gel-stimulants/durex-gel-stimul.jpg',
									'picture-big' => 'assets/images/gel-stimulants/durex-gel-stimul-big.jpg',
									'name' => 'Durex',
									'description' => 'Gel stimulant est enrichi aux extraits de Guarana connu pour ses vertus tonifiantes et stimulantes.',
									'definition' => 'Durex Play gel stimulant est enrichi aux extraits de Guarana connu pour ses vertus tonifiantes et stimulantes. Conseils d\'utilisation :
Ouvrir le bouchon doseur.Frottez un peu de gel Durex Play massage dans le creux de vos mains avant d\'appliquer',
									'reference-store' => '4515456',
									'disponible' => '25',
									'prix' => '5.50',
								 	'prixLitre' => 41.55,
									'linkSite' => 'www.durex.com'
									),

					'gel3' => array(
									'picture' => 'assets/images/gel-stimulants/kibio.jpg',
									'picture-big' => 'assets/images/gel-stimulants/kibio-big.jpg',
									'name' => 'Kibio',
									'description' => 'Gel soin douche stimulant 200ml Kibio',
									'definition' => 'Ce gel est sans savon,  grace à ses ingrédients végétaux issus de l\'agriculture biologique végétale hydrate et protège l\’épiderme… A usage quotidien.',
									'reference-store' => '4515148',
									'disponible' => '18',
									'prix' => '6.55',
								 	'prixLitre' => 37.95,
									'linkSite' => 'www.kibio.com'
									),
									
					'gel4' => array(
									'picture' => 'assets/images/gel-stimulants/gel-baits.jpg',
									'picture-big' => 'assets/images/gel-stimulants/gel-baits-big.jpg',
									'name' => 'GEL BAITS',
									'description' => 'LIQUIDE GEL BAITS STIMULANT & ENHANCER',
									'definition' => 'Ce mélange est un puissant booster pour augmenter l’attraction et la stimulation alimentaire. Formulé par F. Warwick, J. Cann il a fait ses preuves en pêche depuis des années. A mélanger avec de l’amorce, pellets, bouillettes, hookbait ou dans un sac PVA. Bouteilles de 250ml. Un liquide stimulant pour chaque parfum de Gel baits.',
									'reference-store' => '4511258',
									'disponible' => '22',
									'prix' => '5.55',
								 	'prixLitre' => 42.15,
									'linkSite' => 'www.gels-baits.com'
									),		
									
					'gel5' => array(
									'picture' => 'assets/images/gel-stimulants/kamasutra.jpg',
									'picture-big' => 'assets/images/gel-stimulants/kamasutra-big.jpg',
									'name' => 'KamaSutra',
									'description' => 'Gel Stimulant Chauffant 15ml',
									'definition' => 'Kamasutra cree ce Gel chauffant pour satisfaire le désir avec des sensations que vous avez seulement osé imaginer. Ce gel émoustillant doux, conçu exclusivement pour les femmes, intensifie l’excitation intime féminine et encourage merveilleusement le renouvellement du plaisir sensuel. Une formule unique d’herbes stimulantes parmi les plus reconnues de la nature, amplifiant le plaisir sexuel, ce gel est conçu pour fournir des résultats optimaux, vous propulsant avec bonheur aux limites du plaisir et au-delà.',
									'reference-store' => '4511581',
									'disponible' => '28',
									'prix' => '5.85',
								 	'prixLitre' => 41.25,
									'linkSite' => 'www.kamaSutra.com'
									),	
										
					'gel6' => array(
									'picture' => 'assets/images/gel-stimulants/oriflame.jpg',
									'picture-big' => 'assets/images/gel-stimulants/oriflame-big.jpg',
									'name' => 'Oriflame',
									'description' => 'Gel Douche Stimulant Swedish Spa',
									'definition' => 'Gel revigorant au parfum stimulant marin, enrichi à l\'HydraCare+ adoucissant, en extraits vivifiants d’Algues marines et en micro-perles stimulantes. Vous allez adorer cette mousse onctueuse sous la douche pour éveiller le corps et l\'esprit. 200  ml.',
									'reference-store' => '4511777',
									'disponible' => '31',
									'prix' => '4.35',
								 	'prixLitre' => 40.55,
									'linkSite' => 'www.oriflame.com'
									)									
																								
					);

?>