<?php
/*----------------------------------         tableau Produit     ----------------------------------------------*/					
$produit = array( 
				'cho001' => array( 									
								 'images' => 'assets/images/c0.jpg',
								 'imagesBig' => 'assets/images/c00.jpg',
								 'nom' => 'Kerasoin',
								 'description' => 'Shampooing technique apres coloration',
								 'definition' => 'Shampooing technique après coloration de la marque Kérasoin.Le shampooing technique après coloration de la marque
                                                  Kérasoin est au PH acide. Le shampooing technique après coloration de la marque Kérasoin utilise uniquement après
                                                  la coloration  pour régler le PH des cheveux. Le shampooing technique après coloration de la marque Kérasoin
                                                   procure douceur et résistance  à vos cheveux, facilite le démêlage e Le shampooing technique après col',
								 'referenceBoutique' => 4986651,
								 'disponible' => 120,
								 'prix' => '3.33',
								 'prixLitre' => 39.33,
								 'linkSite' => 'www.kerasoin.com'
								 ) ,
                'cho002' => array(
                                'images' => 'assets/images/c2.jpg',
                                'imagesBig' => 'assets/images/c22.jpg',
                                'nom' => 'Eugène Perma',
                                'description' => 'Shampooing purifiant Pure 250ml ',
                                'definition' => 'Shampooing technique après coloration de la marque Kérasoin.Le shampooing technique après coloration de la marque
                                                              Kérasoin est au PH acide. Le shampooing technique après coloration de la marque Kérasoin utilise uniquement après
                                                              la coloration  pour régler le PH des cheveux. Le shampooing technique après coloration de la marque Kérasoin
                                                               procure douceur et résistance  à vos cheveux, facilite le démêlage e Le shampooing technique après col',
                                'referenceBoutique' => 4986651,
                                'disponible' => 120,
                                'prix' => '3.95',
                                'prixLitre' => 39.33,
                                'linkSite' => 'www.kerasoin.com'
                                ) ,
                'cho003' => array(
                                'images' => 'assets/images/c4.jpg',
                                'imagesBig' => 'assets/images/c44.jpg',
                                'nom' => ' Wella',
                                'description' => 'Shampooing cheveux gras purifiant  Eugène',
                                'definition' => 'Shampooing technique après coloration de la marque Kérasoin.Le shampooing technique après coloration de la marque
                                                              Kérasoin est au PH acide. Le shampooing technique après coloration de la marque Kérasoin utilise uniquement après
                                                              la coloration  pour régler le PH des cheveux. Le shampooing technique après coloration de la marque Kérasoin
                                                               procure douceur et résistance  à vos cheveux, facilite le démêlage e Le shampooing technique après col',
                                'referenceBoutique' => 4986651,
                                'disponible' => 120,
                                'prix' => '2.95',
                                'prixLitre' => 39.33,
                                'linkSite' => 'www.kerasoin.com'
                                ) ,
                'cho004' => array(
                                'images' => 'assets/images/c6.jpg',
                                'imagesBig' => 'assets/images/c66.jpg',
                                'nom' => 'Softsheen Carson',
                                'description' => 'Shampooing volume pour cheveux fins',
                                'definition' => 'Shampooing technique après coloration de la marque Kérasoin.Le shampooing technique après coloration de la marque
                                                              Kérasoin est au PH acide. Le shampooing technique après coloration de la marque Kérasoin utilise uniquement après
                                                              la coloration  pour régler le PH des cheveux. Le shampooing technique après coloration de la marque Kérasoin
                                                               procure douceur et résistance  à vos cheveux, facilite le démêlage e Le shampooing technique après col',
                                'referenceBoutique' => 4986651,
                                'disponible' => 120,
                                'prix' => '8.21',
                                'prixLitre' => 39.33,
                                'linkSite' => 'www.kerasoin.com'
                                ) ,
                'cho005' => array(
                                'images' => 'assets/images/c3.jpg',
                                'imagesBig' => 'assets/images/c33.jpg',
                                'nom' => 'Brilliance - Wella',
                                'description' => 'Shampooing pour cheveux normaux originel',
                                'definition' => 'Shampooing technique après coloration de la marque Kérasoin.Le shampooing technique après coloration de la marque
                                                              Kérasoin est au PH acide. Le shampooing technique après coloration de la marque Kérasoin utilise uniquement après
                                                              après col',
                                'referenceBoutique' => 4986651,
                                'disponible' => 120,
                                'prix' => '4.99',
                                'prixLitre' => 39.33,
                                'linkSite' => 'www.kerasoin.com'
                                 ) ,
				'cho006' => array(
                                'images' => 'assets/images/c5.jpg',
                                'imagesBig' => 'assets/images/c55.jpg',
                                'nom' => 'Eugène Perma',
                                'description' => 'Shampooing anti-pelliculaire Clean ',
                                'definition' => 'Shampooing technique après coloration de la marque Kérasoin.Le shampooing technique après coloration de la marque
                                                              la coloration  pour régler le PH des cheveux. Le shampooing technique après coloration de la marque Kérasoin
                                                               rès col',
                                'referenceBoutique' => 4986651,
                                'disponible' => 120,
                                'prix' => '4.70',
                                'prixLitre' => 39.33,
                                'linkSite' => 'www.kerasoin.com'
								 )    
					
					);
					
					
					
					
/*----------------------------------         tableau USER     ---------------------------------------------------*/					
					
$users =  array(
				'1' =>array(
							'dateInscription'=> '13/02/2010 07:25:15',
							'sexe' => 'homme',
							'nom' => 'Jean',
							'prenom' => "Phillipe",
							'email' => 'jean.phillipe@gmail.com',
							'password'=> '12345678',
							'phone'=> '5146528998',
							'favorite' => array(
												'Shampoing',
												'Laque',
												'Mousse',
												'Soin',
												'Volumisant',
												'Gel'
												)
							),

				'2' =>array(
							'dateInscription'=> '13/02/2010 17:05:45',
							'groupe' => "Trousiem",
							'sexe' => 'famme',
							'nom' => 'Anni',
							'prenom' => 'Lopez',
							'email' => 'anni@yahoo.com',
							'password'=> '1233',
							'phone'=> '5141112222',
							'favorite' => array(
											'Shampoing',
											'Laque',
											'Mousse'
											)
							)
					); 

?>