<?php

$laque_coiffant = array(
					'laq-coi1' => array(
									'picture' => 'assets/images/laque-coiffante/evoluderm.jpg',
									'picture-big' => 'assets/images/laque-coiffante/evoluderm-big.jpg',
									'name' => 'Evoluderm',
									'description' => 'LAQUE COIFFANTE HAIR SPRAY EFFET LONGUE DURER',
									'definition' => "La laque coiffante effet longue durer de fixation forte Hair Spray Evoluderm a ete spécialement formuler pour fixer les mouvements de votre coiffure, tout en souplesse, grâce  sa diffusion fi ne et régulière. Séchage rapide et finition",
									'reference-store' => '4515485',
									'disponible' => '37',
									'prix' => '3.90',
								 	'prixLitre' => 40.75,
									'linkSite' => 'www.evoluderm.com'													
									),

					'laq-coi2' => array(
									'picture' => 'assets/images/laque-coiffante/furterer.jpg',
									'picture-big' => 'assets/images/laque-coiffante/furterer-big.jpg',
									'name' => 'RENER FURTERER',
									'description' => 'LAQUE COIFFANTE DE FINITION 300ML',
									'definition' => "Permet de fixer instantanément la coiffure tout en souplesse. Utilisée ne touche de finition, la laque maintient durablement la coiffure puis s'élimine au brossage sans laisser de résidus. ",
									'reference-store' => '4515114',
									'disponible' => '19',
									'prix' => '4.50',
								 	'prixLitre' => 21.95,
									'linkSite' => 'www.furterer.com'
									),

					'laq-coi3' => array(
									'picture' => 'assets/images/laque-coiffante/lavera.jpg',
									'picture-big' => 'assets/images/laque-coiffante/lavera-big.jpg',
									'name' => 'Lavera',
									'description' => 'SPRAY COIFFANT BIO LAQUE VOLUME ET BRILLANCE 150ML',
									'definition' => "Cosmétique bio soin des cheveux spray laque volume Lavera. Laque volume & brillance - fixation extra forte, aloé véra bio et bambou bio . Une laque à effet volume pour un style qui dure.",
									'reference-store' => '4512258',
									'disponible' => '50',
									'prix' => '7.55',
								 	'prixLitre' => 38.95,
									'linkSite' => 'www.levera.com'
									),
									
					'laq-coi4' => array(
									'picture' => 'assets/images/laque-coiffante/black-beautiful.jpg',
									'picture-big' => 'assets/images/laque-coiffante/black-beautiful-big.jpg',
									'name' => 'BLACK & BEAUTIFUL',
									'description' => "LAQUE COIFFANTE A L'HUILE D'OLIVES",
									'definition' => "Vaporisateur de 467ml de laque coiffante à l'huile d'olives vierge et à la vitamine E.",
									'reference-store' => '4514148',
									'disponible' => '25',
									'prix' => '5.48',
								 	'prixLitre' => 41.25,
									'linkSite' => 'www.black-beautiful.com'
									),		
									
					'laq-coi5' => array(
									'picture' => 'assets/images/laque-coiffante/leonor.jpg',
									'picture-big' => 'assets/images/laque-coiffante/leonor-big.jpg',
									'name' => 'LEONOR GREYL',
									'description' => 'LAQUE SOUPLE CHEVEUX LEONOR GREYL',
									'definition' => "LAQUE SOUPLE CHEVEUX LEONOR GREYL - Volume : 125 mlPour un effet savamment naturel! La LAQUE SOUPLE CHEVEUX de LEONOR GREYL est un soin de coiffage.",
									'reference-store' => '4513030',
									'disponible' => '30',
									'prix' => '5.55',
								 	'prixLitre' => 40.25,
									'linkSite' => 'www.leonor-greyl.com'
									),	
										
					'laq-coi6' => array(
									'picture' => 'assets/images/laque-coiffante/jacques.jpg',
									'picture-big' => 'assets/images/laque-coiffante/jacques-big.jpg',
									'name' => 'Jacques Dessange',
									'description' => 'Laque professionnelle Brume seche fixation normale 400ml',
									'definition' => "Les 1ères laques brume sèche, diffusion non mouillante, non alourdissante qui offre pour chaque type de coiffure, une fixation adaptée.",
									'reference-store' => '4511888',
									'disponible' => '32',
									'prix' => '4.15',
								 	'prixLitre' => 40.15,
									'linkSite' => 'www.jacques-dessange.com'
									)									
																								
					);

?>