<?php

$volumisants = array(
					'volu1' => array(
									'picture' => 'assets/images/volumisant/lisap.jpg',
									'picture-big' => 'assets/images/volumisant/lisap-big.jpg',
									'name' => 'Lisap',
									'description' => 'Shampoing volumisant pour cheveux fins',
									'definition' => "Shampoing volumisant Lisap Top Care Fine C1 1000ml lave délicatement, améliore le coiffage et la tenue de la coiffure.

Grâce aux principes actifs corporisants, Aminocare Complex et à l'extrait de Baobab, il donne un volume incroyable associé à une grande brillance et légèreté.",
									'reference-store' => '4511136',
									'disponible' => '48',
									'prix' => '4.95',
								 	'prixLitre' => 44.75,
									'linkSite' => 'www.lisap.com'													
									),

					'volu2' => array(
									'picture' => 'assets/images/volumisant/john-master.jpg',
									'picture-big' => 'assets/images/volumisant/john-master-big.jpg',
									'name' => 'JOHN MASTERS ORGANICS',
									'description' => 'Soin de cuir chevelure Epaississant et Volumisant',
									'definition' => "Soin sans rinçage en spray, ce produit bio pour cheveux permet d'améliorer la santé du cuir chevelu en facilitant l'assimilation des nutriments, en stimulant la micro-circulation, en équilibrant la production de sébum et en éliminant les radicaux libres.",
									'reference-store' => '4515141',
									'disponible' => '31',
									'prix' => '4.88',
								 	'prixLitre' => 31.12,
									'linkSite' => 'www.john-masters.com'
									),

					'volu3' => array(
									'picture' => 'assets/images/volumisant/wella.jpg',
									'picture-big' => 'assets/images/volumisant/wella-big.jpg',
									'name' => "Wella",
									'description' => 'Bain volumisant pour cheveux fins',
									'definition' => "Bain volumisant pour cheveux fins Action ciblée : Renforce les cheveux fins Nettoie les cheveux en douceur Apporte un volume longue tenue à la chevelure",
									'reference-store' => '4512192',
									'disponible' => '42',
									'prix' => '6.45',
								 	'prixLitre' => 39.25,
									'linkSite' => 'www.wella.com'
									),
									
					'volu4' => array(
									'picture' => 'assets/images/volumisant/revlone.jpg',
									'picture-big' => 'assets/images/volumisant/revlone-big.jpg',
									'name' => 'Revlon',
									'description' => "Equave 2 Soin volumisant instantaner pour cheveux fins 500 ml",
									'definition' => "Formule au Raisin et Thé vert.Soin volumisateur instantaner sans rinçage pour cheveux fins et mous 500 ml.",
									'reference-store' => '4514226',
									'disponible' => '26',
									'prix' => '5.56',
								 	'prixLitre' => 41.36,
									'linkSite' => 'www.revlon.com'
									),		
									
					'volu5' => array(
									'picture' => 'assets/images/volumisant/biosilk.jpg',
									'picture-big' => 'assets/images/volumisant/biosilk-big.jpg',
									'name' => 'Biosilk',
									'description' => 'Apres-shampoing volumateur - Cheveux fins',
									'definition' => "etrouvez une chevelure volumineuse ! L’après-shampoing volumumateur Biosilk rend vos cheveux brillants et plein de vie !",
									'reference-store' => '4513232',
									'disponible' => '32',
									'prix' => '5.32',
								 	'prixLitre' => 40.32,
									'linkSite' => 'www.biosilk.com'
									),	
										
					'volu6' => array(
									'picture' => 'assets/images/volumisant/triaxon.jpg',
									'picture-big' => 'assets/images/volumisant/triaxon-big.jpg',
									'name' => 'Triaxon',
									'description' => 'Spray volumisant pour cheveux Ionic XP de Triaxon',
									'definition' => "Le fixatif volumisant pour les cheveux Triaxon Ionic XP (8 oz.) peut être utilisé comme fixatif, gel à vaporiser ou rehausseur de brillance sur les cheveux secs ou humides! Cette formule multifonctionnelle aide à donner du volume, à sculpter et à faire briller les cheveux.",
									'reference-store' => '4532154',
									'disponible' => '46',
									'prix' => '5.16',
								 	'prixLitre' => 43.14,
									'linkSite' => 'www.triaxon.com'
									)									
																								
					);

?>